config/routes.rb
Rails.application.routes.draw do
  # get 'evals/new'
  # get 'evals/edit'
  # get 'stores/new'
  # get 'stores/edit'
  # get 'users/new'
  # get 'users/edit'
  # get 'top/index'
  # get 'top/login'
  get 'top/login_form'
  post 'top/login'
  get 'top/logout'
  #get 'top/search_form'
  #get 'top/search'
  get 'search', to: 'top#search'
  resources :evals
  resources :stores
  resources :users
  resources :top, only: [:index]
  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eval.rb
class Eval < ApplicationRecord
end

app/models/ride.rb
class Ride < ApplicationRecord
    enum ride_area:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    
    validates :uname, presence: true, uniqueness: :true
    validates :password, presence: true, confirmation: true
    
    has_many :evals, dependent: :destroy
    has_many :stores, through: :evals
    
    attr_accessor :password, :password_confirmation
    
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
    
    def self.authenticate(uname, pass)
        user = find_by(uname: uname)
        if user and BCrypt::Password.new(user.pass) == pass
            true
        else
            false
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
        if session[:login_uname]
            User.find_by(uname: session[:login_uname])
        end
    end
    helper_method :current_user
end

app/controllers/evals_controller.rb
class EvalsController < ApplicationController
  def index
    @evals = Eval.all
  end
  
  def new
    @eval = Eval.new
  end
  
  def create
    evals = Eval.new(ceval: params[:eval][:ceval], cmt: params[:eval][:cmt])
    evals.save
    redirect_to top_index_path
  end
  
  def destroy
    evals = Eval.find(params[:id])
    evals.destroy
    redirect_to top_index_path
  end

  def edit
    @eval = Eval.find(params[:id])
  end
  
  def update
    eval = Eval.find(params[:id])
    eval.update(ceval: params[:eval][:ceval], cmt: params[:ceval][:cmt])
    redirect_to top_index_path
  end
  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end
  
  def new
    @store = Store.new
  end
  
  def create
    store = Store.new(sname: params[:store][:sname], addr1: params[:store][:addr1], addr2: params[:store][:addr2], addr3: params[:store][:addr3], tel: params[:store][:tel], open: params[:store][:open],close: params[:store][:close],
                      eval1: params[:store][:eval1], eval2: params[:store][:eval2], eval3: params[:store][:eval3], eval4: params[:store][:eval4], eval5: params[:store][:eval5])
    store.save
    redirect_to top_index_path
  end
  
  def destroy
    store = Store.find(params[:id])
    store.destroy
    redirect_to top_index_path
  end

  def edit
    @store = Store.find(params[:id])
  end
  
  def update
    store = Store.find(params[:id])
    store.update(sname: params[:store][:sname], addr1: params[:store][:addr1], addr2: params[:store][:addr2], addr3: params[:store][:addr3], tel: params[:store][:tel], open: params[:store][:open],close: params[:store][:close],
                 eval1: params[:store][:eval1], eval2: params[:store][:eval2], eval3: params[:store][:eval3], eval4: params[:store][:eval4], eval5: params[:store][:eval5])
    redirect_to top_index_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @stores = Store.all
    @evals = Eval.limit(1)
    params[:checklist] ||= {"eval1"=>"0", "eval2"=>"0", "eval3"=>"0", "eval4"=>"0", "eval5"=>"0"}
    #@check = params[:checklist]
  end
  
  def login_form
    render :login
  end

  def login
    if User.authenticate(params[:uname], params[:pass])
      session[:login_uname] = params[:uname]
      redirect_to root_path
    else
      render :login
    end
  end
  
  def logout
    session.delete(:login_uname)
    redirect_to root_path
  end
  
  def search
    @evals = Eval.limit(3)
    @ride = params[:prefecture].values[0]
    c = []
    #@check = params[:checklist]
    params[:checklist].each do | di1,di2 |
      if di2 == "1"
        c.push("#{di1} = 1")
      end
    end
    
    c.push("addr1 = '#{@ride}'")
      
    if c == []
      @stores = Store.all
    else
      search_cond = [ c.join(' AND ') ]
      @stores = Store.where(search_cond)
    end
    render :index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(
    uname: params[:user][:uname], 
    password: params[:user][:password], 
    password_confirmation: params[:user][:password_confirmation])
    
    if @user.save
      redirect_to root_path
    else
      #@user.pass = ""
      logger.debug("あああ")
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(uid: params[:user][:uname])
      #flash[:notice] = '内容が編集されました'
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evals_helper.rb
module EvalsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/evals/edit.html.erb
<h1>Evals#edit</h1>
<p>Find me in app/views/evals/edit.html.erb</p>

app/views/evals/new.html.erb
<h1>評価ページ</h1>

<%= form_for @eval, url: {action: :create} do |f| %>

  <div class="form-group row" id="star">
    <%= f.label :ceval,'評価 ', class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :ceval, id: :review_star %>
  </div>
  
  <script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'eval[ceval]',
    half: true
  });
  </script>  

    <%= f.label :cmt, 'コメント' %>
    <%= f.text_area :cmt, size: "100x15" %>

  <%= f.submit '投稿する' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Koronabi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <div id="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/stores/edit.html.erb
<%= form_for @store, url: {action: :update} do |s| %>
  <p>
      <%= s.label :sname, "店名" %>
      <%= s.text_field :sname %><br>
      <%= s.label :addr1, "都道府県" %>
      <%= s.text_field :addr1 %>
      <%= s.label :addr2, "市区町村" %>
      <%= s.text_field :addr2 %>
      <%= s.label :addr3, "番地・建物名" %>
      <%= s.text_field :addr3 %><br>
      <%= s.label :tel, "電話番号" %>
      <%= s.text_field :tel %><br>
      <%= s.label :open, "営業時間" %>
      <%= s.time_field :open %>
      <%= s.label :close, "~" %>
      <%= s.time_field :close %>
  </p>
  <p>
      <%= s.check_box :eval1, {}, 1, 0 %>
      <%= s.label :eval1, "体温検査" %>
  </p>
  <p>
      <%= s.check_box :eval2, {}, 1, 0 %>
      <%= s.label :eval2, "消毒液の設置" %>
  </p>
  <p>
      <%= s.check_box :eval3, {}, 1, 0 %>
      <%= s.label :eval3, "マスク着用" %>
  </p>
  <p>
      <%= s.check_box :eval4, {}, 1, 0 %>
      <%= s.label :eval4, "個室・しきり" %>
  </p>
  <p>
      <%= s.check_box :eval5, {}, 1, 0 %>
      <%= s.label :eval5, "非接触型決済の設置" %>
  </p>
  <p>
      <%= s.submit '登録' %>
  </p>
<% end %>

app/views/stores/new.html.erb
<お店情報登録>

<%= form_for @store, url: {action: :create} do |s| %>
  <p>
      <%= s.label :sname, "店名" %>
      <%= s.text_field :sname %><br>
      <%= s.label :addr1, "都道府県" %>
      <%= s.text_field :addr1 %>
      <%= s.label :addr2, "市区町村" %>
      <%= s.text_field :addr2 %>
      <%= s.label :addr3, "番地・建物名" %>
      <%= s.text_field :addr3 %><br>
      <%= s.label :tel, "電話番号" %>
      <%= s.text_field :tel %><br>
      <%= s.label :open, "営業時間" %>
      <%= s.time_field :open %>
      <%= s.label :close, "~" %>
      <%= s.time_field :close %>
  </p>
  <p>
      <%= s.check_box :eval1, {}, 1, 0 %>
      <%= s.label :eval1, "体温検査" %>
  </p>
  <p>
      <%= s.check_box :eval2, {}, 1, 0 %>
      <%= s.label :eval2, "消毒液の設置" %>
  </p>
  <p>
      <%= s.check_box :eval3, {}, 1, 0 %>
      <%= s.label :eval3, "マスク着用" %>
  </p>
  <p>
      <%= s.check_box :eval4, {}, 1, 0 %>
      <%= s.label :eval4, "個室・しきり" %>
  </p>
  <p>
      <%= s.check_box :eval5, {}, 1, 0 %>
      <%= s.label :eval5, "非接触型決済の設置" %>
  </p>
  <p>
      <%= s.submit '登録' %>
  </p>
<% end %>

app/views/top/index.html.erb
<div id="header">
<font id="title">コロナビ</font>
<div id="header-right">
<% if current_user %>
    <%= session[:login_uname] %>さん
    <%= link_to 'ログアウト', top_logout_path %>
<% else %>
    <%= link_to 'ログイン', top_login_form_path %>
    または
    <%= link_to 'ユーザ登録', new_user_path  %>
<% end %>
</div>
</div>

<div class="box1">
<%= form_tag(search_path, method: "get") do %>
     エリア
    <p>
      <%= select :prefecture, {}, Ride.ride_areas.keys,{ selected: @ride } %><br>
    </p>
  対策項目
  <p>
  <%= check_box :checklist, "eval1", { checked: params[:checklist].values[0] == "1" }%>体温検査の実施
  </p>
  <p>
  <%= check_box :checklist, "eval2", { checked: params[:checklist].values[1] == "1" }%>消毒液の設置 
  </p>
  <p>
  <%= check_box :checklist, "eval3", { checked: params[:checklist].values[2] == "1" }%>マスク着用の必要 
  </p>
  <p>
  <%= check_box :checklist, "eval4", { checked: params[:checklist].values[3] == "1" }%>個室・しきりがある 
  </p>
  <p>
  <%= check_box :checklist, "eval5", { checked: params[:checklist].values[4] == "1" }%>非接触型決済ツール
  </p>
<%= submit_tag "検索" %>
</p>
<% end %>
</div>

<h1>店舗一覧</h1>
<% @stores.each do |s| %>
  <p>
      店名: <%= s.sname %><br>
      住所: <%= s.addr1 %><%= s.addr2 %><%= s.addr3 %><br>
      電話番号: <%= s.tel %><br>
      営業時間: <%= s.open %>~<%= s.close %><br>
      コロナ対策（1：対策あり、0：対策なし）<br>
      体温検査: <%= s.eval1 %><br>
      消毒液の設置: <%= s.eval2 %><br>
      マスク着用: <%= s.eval3 %><br>
      個室・しきり: <%= s.eval4 %><br>
      非接触型決済: <%= s.eval5 %><br>
<% if current_user %>
      <%= link_to '編集', edit_store_path(s) %>
      <%= link_to '削除', store_path(s), method: :delete %>
      <%= link_to 'お店の評価をする', new_eval_path %>
<% end %></h1>
  </p>

<% end %>

  <% @evals.each do |e| %>
    <div class="row posts">
      <div class="col-md-6 mb-3">
        <div class=" posts-content">
          <h4 class="mb-3">評価：<%= e.ceval %>点 | <%= e.cmt %></h4>

         <div id="star-rate-<%= e.id %>"></div>
          <script>
          $('#star-rate-<%= e.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= e.ceval %>
          });
          </script> 
          <%= link_to '編集', edit_eval_path(e) %>
          <%= link_to '削除', eval_path(e), method: :delete %>
        </div>
      </div>
    </div>
<% end %>
<hr>
<% if current_user %>
<%= link_to 'お店を追加する', new_store_path  %>
<% end %>

app/views/top/login.html.erb
<h1>ログイン</h1>

<%= form_tag '/top/login', method: :post do %>
<p>
    <%= label_tag :uname, 'ユーザーID' %>
    <%= text_field_tag :uname %></p>
<p>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %></p>
    <%= submit_tag 'ログイン' %>
<% end %>
<p>
登録されてない方は
<%= link_to '新規登録', new_user_path  %>
</p>

app/views/top/search.html.erb
<% @stores.each do |s| %>
  <li><%= s.sname %><br>
  eval1: <%= s.eval1 %><br>
  eval2: <%= s.eval2 %><br>
  eval3: <%= s.eval3 %><br>
  eval4: <%= s.eval4 %><br>
  eval5: <%= s.eval5 %></li>
<% end %>

<%= link_to 'トップへ', root_path %>

app/views/users/_footer.html.erb
<div id="copyright">Copyright © コロナビ. All Rights Reserved.</div>

app/views/users/_header.html.erb
<div id="header-banner-area">
コロナビ
</div>
    

app/views/users/edit.html.erb
<%= form_with model: @user ,action: :update do |f| %>
  <p><%= f.label :uname, 'ユーザ名: ' %>
  <%= f.text_field :uname %></p>
  <%= f.submit "編集" %>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= form_for @user, url: {action: :create} do |f| %>
<p>  
    <%= f.label :uname, 'ユーザーID' %>
    <%= f.text_field :uname %></p>
<p>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password %></p>
<p>
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation %></p>
<p>

    <%= f.submit '登録' %>
</p>
<% end %>
<p>
登録済みの方は
<%= link_to 'ログイン', top_login_form_path %>
</p>